apiVersion: v1
kind: ConfigMap
metadata:
  name: quotes-aggregator-config
data:
  PRIMARY_QUOTE_URL: "https://api.quotable.io/random"
  SECONDARY_QUOTE_URL: "https://api.quotable.io/random"
  REQUEST_TIMEOUT: "5"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
